name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.10'
          # mdbook-version: 'latest'
      - name: Build API Docs for vanetza-sys
        run: |
          cargo doc --package vanetza-sys --features docs-only --no-deps
          mv target/doc vanetza-sys-docs
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url='"'"'vanetza_sys/index.html'"'"'" /></head><body></body></html>' > vanetza-sys-docs/index.html
      - name: Build API Docs for vanetza
        run: |
          cargo doc --package vanetza --features docs-only --no-deps
          mv target/doc vanetza-docs
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url='"'"'vanetza/index.html'"'"'" /></head><body></body></html>' > vanetza-docs/index.html
      - name: Build Dev Guide
        run: cd dev-guide && mdbook build
      - name: Publish API doc for vanetza-sys
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vanetza-sys-docs
          publish_branch: vanetza-sys-api-pages
      - name: Publish API doc for vanetza
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vanetza-docs
          publish_branch: vanetza-api-pages
      - name: Deploy Dev Guide
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dev-guide/book
          publish_branch: dev-guide-pages
